# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 060c25e8c5dd4cb8a8cd996b71c59e847837c2985f512b48b8beb0fbccadc646b8c4178808b08990f7afc4e55e8eb1997b377a0215dfe15aacea58be723ad50f

test:
  secret_key_base: ddb705afcdf74c0360f6b607ae8bcb959f29a9e6da59b75e64f33f965b157b099e89e88c59fa30895746310f8faee1ed5eda4d038b0cf908bd4ba413528f0c25

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
